### ISSUE TITLE
Issue with Init.lua

### ISSUE THREAD

**Issue by AssuredDust640** [patrickeasters/nodemcu-sensor-mqtt#1]
I'm getting this error message when uploading the lua files onto the board.

Setting up wifi
lua: init.lua:17: bad argument #1 to 'config' (config table not found!)
stack traceback:
	[C]: in function 'config'
	init.lua:17: in main chunk
	[C]: ?

Any ideas?

**Comment by patrickeasters** [comment]
I probably should make this clearer in the README, but did you rename your secrets file to `secrets.lua` (without `.example` in the filename)?

**Comment by AssuredDust640** [comment]
Sorry, was away for work for a few days. Yes, the secrets.lua file has the "example" removed.

Was there anything specific in the Cloud Build Service to be mindful of? I chose Master branch, should it perhaps been the Dev branch?

**Comment by patrickeasters** [comment]
I built my firmware off master probably close to a year ago at this point. I think the `wifi.sta.config()` function is expecting a table now instead of those parameters. I can look at this later this evening once the kiddo is asleep and I can better test it. But if you want to try and fix it yourself, here's something to try.

Update the secrets.lua file to configure the SSID and PSK in a table:
```
WIFI_CONFIG={}
WIFI_CONFIG.ssid="mynetwork"
WIFI_CONFIG.pwd="password"
```

Then you can change the `wifi.sta.config` line in init.lua to use the new table:
```
wifi.sta.config(WIFI_CONFIG)
```

Hope that helps! If that ends up working, you're welcome to submit a pull request

**Comment by AssuredDust640** [comment]
Ok, I'll give this a try tonight and report back. thanks again for all your assistance

**Comment by patrickeasters** [comment]
Were you able to test this yourself? I updated my NodeMCU to the latest firmware and made the code changes I suggested above. That seems to be working now.

Thanks for pointing this out!

**Comment by AssuredDust640** [comment]
Sadly I haven't yet as I ran out of NodeMCUs to test it on and had family visiting, but next week will get back to it. Thanks for the tips and seeing as you have it working I imagine I'll have no further issues. Thanks for all the help

**Comment by AssuredDust640** [comment]
Made all the changes and she's working like a gem. Thanks so much for your help with this. My first time dealing with lua files so very happy to now have a better grasp on their workings.
